export type {
  JobStatus,
  EmploymentType,
  SkillPriority,
  ScreeningQuestion,
  JobRequiredSkillDto,
  JobRequirementDto,
  CreateJobVacancyDto,
  UpdateJobVacancyDto,
  JobVacancyDetail,
  RecruiterJobListItem,
  JobComplianceCheckResult,
  ScoreWeightConfig,
  PaginatedResult,
} from '@recruitment-platform/shared';
